### ISSUE TITLE
how to create parity file using account number and password,to connect with Nile network?

### ISSUE THREAD

**Issue by AyushVerma2** [oceanprotocol/squid-java#130]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ yes] I am running the latest version

## Current Behavior

What is the current behavior? Please provide as many details as possible.

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Step to Reproduce the problem

Please provide detailed steps for reproducing the issue.
I am getting below error while trying to connect with Nile network.
Can you please tell me how to create the accounts/parity/file, if I know my account and password.

## Failure Logs

com.oceanprotocol.squid.exceptions.DDOException: Error registering Asset.

	at com.oceanprotocol.squid.manager.OceanManager.registerAsset(OceanManager.java:266)
	at com.oceanprotocol.squid.api.impl.AssetsImpl.create(AssetsImpl.java:50)
	at com.oceanprotocol.squid.api.impl.AssetsImpl.create(AssetsImpl.java:55)
	at com.oceanprotocol.squid.api.AssetsApiIT.create(AssetsApiIT.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.oceanprotocol.squid.exceptions.DIDRegisterException: Error registering DID 0de6f9044cce4f3093e7c248cfa634cf8df5e6727ca14d93b72a12b48ecce1cf
	at com.oceanprotocol.squid.manager.OceanManager.registerDID(OceanManager.java:177)
	at com.oceanprotocol.squid.manager.OceanManager.registerAsset(OceanManager.java:258)
	... 26 more
Caused by: java.lang.RuntimeException: Error processing transaction request: Account password is invalid or account does not exist.
	at org.web3j.tx.TransactionManager.processResponse(TransactionManager.java:67)
	at org.web3j.tx.TransactionManager.executeTransaction(TransactionManager.java:51)
	at org.web3j.tx.ManagedTransaction.send(ManagedTransaction.java:87)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:291)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:275)
	at org.web3j.tx.Contract.executeTransaction(Contract.java:269)
	at org.web3j.tx.Contract.lambda$executeRemoteCallTransaction$3(Contract.java:321)
	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
	at com.oceanprotocol.squid.manager.OceanManager.registerDID(OceanManager.java:172)
	... 27 more

**Comment by josepablofm78** [comment]
Hi Ayush,

in first place, this would be the configuration you need to use Nile. You just need to set the data relative with the main account (address, password, and credentials File)

keeper.url="https://nile.dev-ocean.com"
keeper.gasLimit=4712388
keeper.gasPrice=100000000000
keeper.tx.attempts=50
keeper.tx.sleepDuration=1000

aquarius.url="https://nginx-aquarius.dev-ocean.com"
aquarius-internal.url="https://nginx-aquarius.dev-ocean.com"
brizo.url="https://nginx-brizo.dev-ocean.com"
secretstore.url="https://secret-store.dev-ocean.com"

provider.address="0x376817c638d2a04f475a73af37f7b51a2862d567"

contract.SignCondition.address="0x5a4301F8a7a8A13485621b9B4C82B1E66c112ee2"
contract.HashLockCondition.address="0xB5f2e45e8aD4a1339D542f2defd5095B98054590"
contract.LockRewardCondition.address="0xE30FC30c678437e0e8F78C52dE9db8E2752781a0"
contract.AccessSecretStoreCondition.address="0x45DE141F8Efc355F1451a102FB6225F1EDd2921d"
contract.EscrowReward.address="0xeD4Ef53376C6f103d2d7029D7E702e082767C6ff"
contract.EscrowAccessSecretStoreTemplate.address="0xfA16d26e9F4fffC6e40963B281a0bB08C31ed40C"
contract.OceanToken.address="0x9861Da395d7da984D5E8C712c2EDE44b41F777Ad"
contract.Dispenser.address="0x865396b7ddc58C693db7FCAD1168E3BD95Fe3368"
contract.DIDRegistry.address="0x4A0f7F763B1A7937aED21D63b2A78adc89c5Db23"
contract.ConditionStoreManager.address="0x39b0AA775496C5ebf26f3B81C9ed1843f09eE466"
contract.TemplateStoreManager.address="0x9768c8ae44f1dc81cAA98F48792aA5730cAd2F73"
contract.AgreementStoreManager.address="0x62f84700b1A0ea6Bfb505aDC3c0286B7944D247C"

consume.basePath = "/tmp"

account.main.address="0x...."
account.main.password="..."
account.main.credentialsFile="/path/to/credentials.json"

**Comment by josepablofm78** [comment]
The credential's json file should have been generated when you created your account. If you don't have it, you can generate it again using some tools like:

https://ethereum.stackexchange.com/questions/37524/generate-keystore-file-from-raw-private-key-using-geth 

https://ethereum.stackexchange.com/questions/16797/export-metamask-account-to-json-file

I hope this helps

**Comment by AyushVerma2** [comment]
Even with above-suggested configuration, I am getting an exception while registering an asset.
It looks like https://secret-store.dev-drops.com is down.Error:
com.oceanprotocol.squid.exceptions.DDOException: Error building DDO

	at com.oceanprotocol.squid.manager.BaseManager.buildDDO(BaseManager.java:125)
	at com.oceanprotocol.squid.manager.OceanManager.registerAsset(OceanManager.java:201)
	at com.oceanprotocol.squid.api.impl.AssetsImpl.create(AssetsImpl.java:50)
	at com.oceanprotocol.squid.api.impl.AssetsImpl.create(AssetsImpl.java:55)
	at sg.dex.starfish.integration.squid.AssetsApiIT.create(AssetsApiIT.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.oceanprotocol.squid.exceptions.EncryptionException: Error encrypting Document
	at com.oceanprotocol.squid.manager.SecretStoreManager.encryptDocument(SecretStoreManager.java:58)
	at com.oceanprotocol.squid.manager.BaseManager.buildDDO(BaseManager.java:117)
	... 27 more
Caused by: java.io.IOException: Unable to encrypt document
	at com.oceanprotocol.secretstore.auth.PublisherWorker.encryptDocument(PublisherWorker.java:110)
	at com.oceanprotocol.squid.manager.SecretStoreManager.encryptDocument(SecretStoreManager.java:55)
	... 28 more


Process finished with exit code 255

**Comment by AyushVerma2** [comment]
i am not able to register using squid-java :
<dependency>
			<groupId>com.oceanprotocol</groupId>
			<artifactId>squid</artifactId>
			<version>0.5.3</version>
		</dependency>

Also using the same metadata.json as in the example.
but getting null in PublisherWorker,java ,line no.85..
  log.debug("EVM: Signing documentKeyId");
            signedDocKey = evmDto.signDocumentKeyId(documentKeyId);// this return null:
Actual exception:
com.oceanprotocol.squid.exceptions.DDOException: Error building DDO

	at com.oceanprotocol.squid.manager.BaseManager.buildDDO(BaseManager.java:125)
	at com.oceanprotocol.squid.manager.OceanManager.registerAsset(OceanManager.java:201)
	at com.oceanprotocol.squid.api.impl.AssetsImpl.create(AssetsImpl.java:50)
	at com.oceanprotocol.squid.api.impl.AssetsImpl.create(AssetsImpl.java:55)
	at sg.dex.starfish.integration.squid.AssetsApiIT.create(AssetsApiIT.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.oceanprotocol.squid.exceptions.EncryptionException: Error encrypting Document
	at com.oceanprotocol.squid.manager.SecretStoreManager.encryptDocument(SecretStoreManager.java:58)
	at com.oceanprotocol.squid.manager.BaseManager.buildDDO(BaseManager.java:117)
	... 27 more
Caused by: java.io.IOException: Unable to encrypt document
	at com.oceanprotocol.secretstore.auth.PublisherWorker.encryptDocument(PublisherWorker.java:110)
	at com.oceanprotocol.squid.manager.SecretStoreManager.encryptDocument(SecretStoreManager.java:55)
	... 28 more
