### ISSUE TITLE
Android app test - ERROR AccountsManager Unable to get account

### ISSUE THREAD

**Issue by adonnini** [oceanprotocol/squid-java#138]
Hi Jose',

It looks like the basics of trnasaction creation are working. However, I am getting an " Unable to get account" error. The error log is reported below.

At this point, I am only interested in publishing and retrieving metadata, I could disable any actions related to buy/sell transactions.

Thanks,

Alex

07-20 17:48:21.903: W/System.err(7762): ERROR AccountsManager Unable to get account(0x068Ed00cF0441e4829D9784fCBe7b9e26D4BD8d0) Ocean balance: Empty value (0x) returned from contract
07-20 17:48:21.905: W/System.err(7762): com.android.squid.exceptions.EthereumException: Unable to get account(0x068Ed00cF0441e4829D9784fCBe7b9e26D4BD8d0) Ocean balance
07-20 17:48:21.905: W/System.err(7762): 	at com.android.squid.manager.AccountsManager.getOceanAccountBalance(AccountsManager.java:126)
07-20 17:48:21.905: W/System.err(7762): 	at com.android.squid.manager.AccountsManager.getAccountBalance(AccountsManager.java:87)
07-20 17:48:21.905: W/System.err(7762): 	at com.android.squid.api.impl.AccountsImpl.balance(AccountsImpl.java:46)
07-20 17:48:21.905: W/System.err(7762): 	at com.android.contextq.locationestimation.OceanProtocolLocationEstimation.setUp(OceanProtocolLocationEstimation.java:280)
07-20 17:48:21.905: W/System.err(7762): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1718)
07-20 17:48:21.905: W/System.err(7762): 	at com.android.contextq.ui.MainActivity$OceanProtocolTestTransaction.doInBackground(MainActivity.java:1703)
07-20 17:48:21.905: W/System.err(7762): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
07-20 17:48:21.905: W/System.err(7762): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-20 17:48:21.906: W/System.err(7762): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
07-20 17:48:21.906: W/System.err(7762): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
07-20 17:48:21.906: W/System.err(7762): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
07-20 17:48:21.906: W/System.err(7762): 	at java.lang.Thread.run(Thread.java:764)
07-20 17:48:21.906: W/System.err(7762): Caused by: org.web3j.tx.exceptions.ContractCallException: Empty value (0x) returned from contract
07-20 17:48:21.906: W/System.err(7762): 	at org.web3j.tx.Contract.executeCallSingleValueReturn(Contract.java:246)
07-20 17:48:21.906: W/System.err(7762): 	at org.web3j.tx.Contract.lambda$executeRemoteCallSingleValueReturn$1(Contract.java:313)
07-20 17:48:21.906: W/System.err(7762): 	at org.web3j.tx.-$$Lambda$Contract$oYGWABDpPbmg8SXDB6ogrDJA-Nw.call(Unknown Source:6)
07-20 17:48:21.906: W/System.err(7762): 	at org.web3j.protocol.core.RemoteCall.send(RemoteCall.java:30)
07-20 17:48:21.906: W/System.err(7762): 	at com.android.squid.manager.AccountsManager.getOceanAccountBalance(AccountsManager.java:122)
07-20 17:48:21.906: W/System.err(7762): 	... 11 more
07-20 17:48:21.906: I/MainActivity(7762): - OceanProtocolTestTransaction - doInBackground - Set up Ocean Protocol infrastructure - 
07-20 17:48:21.906: I/MainActivity(7762): - OceanProtocolTestTransaction - doInBackground - Executing Ocean Protocol transaction - 
07-20 17:48:21.908: D/OceanManager(7762):  - registerAsset - metadataEndpoint - https://nginx-aquarius.dev-ocean.com/api/v1/aquarius/assets/ddo/{did}
07-20 17:48:21.908: D/OceanManager(7762):  - registerAsset - metadata.base.files.size() - 1
07-20 17:48:21.908: D/OceanManager(7762):  - registerAsset - metadataService.toString() - com.android.squid.models.service.MetadataService@fe40b22
07-20 17:48:21.908: D/OceanManager(7762):  - registerAsset - authorizationService.toString() - com.android.squid.models.service.AuthorizationService@dc949b3
07-20 17:48:21.908: D/OceanManager(7762):  - registerAsset - getMainAccount().address.toString() - 0x068Ed00cF0441e4829D9784fCBe7b9e26D4BD8d0
07-20 17:48:21.931: D/BaseManager(7762):  - registerAsset - metadataService.toString() - com.android.squid.models.service.MetadataService@fe40b22
07-20 17:48:21.931: D/BaseManager(7762):  - registerAsset - metadataService.metadata.base.files.size() - 1
07-20 17:48:21.931: D/BaseManager(7762):  - registerAsset - filesJson - [{"checksum":"test001","compression":"zip","contentLength":999999,"contentType":"text/csv","encoding":"UTF-8","index":0,"url":"test001"}]
07-20 17:48:21.931: D/BaseManager(7762):  - registerAsset - authorizationService.toString() - com.android.squid.models.service.AuthorizationService@dc949b3
07-20 17:48:21.931: D/BaseManager(7762):  - registerAsset - getMainAccount().address.toString() - 0x068Ed00cF0441e4829D9784fCBe7b9e26D4BD8d0

**Comment by adonnini** [comment]
I think this is the same issue as #136
