### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by tmarble** [oceanprotocol/squid-java#75]
## Expected Behavior

Expect that when the Travis badge says "build passing" that it means integration tests are passing.

## Current Behavior

What is the current behavior? 
- Integration tests are currently _not_ run -- this is already reported in #13 
- Integration tests are failing (this issue)

## Failure Information (for bugs)

Integration tests report:
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   AccountsApiIT.balance:55 » Ethereum Unable to get account(0x00Bd138aBD70e2F009...
[ERROR]   AccountsApiIT.requestTokens:66 » Ethereum Unable to get account(0x00Bd138aBD70...
[ERROR]   AssetsApiIT.setUp:96 » ContractCall Empty value (0x) returned from contract
[ERROR]   AccountsManagerIT.getAccountsBalance:99 » Ethereum Unable to get account(0x00B...
[ERROR]   AssetsManagerIT.publishMetadata:70 » DDO Error building DDO from JSON
[ERROR]   AssetsManagerIT.searchAssets:117 » DDO Error building DDO from JSON
[ERROR]   OceanManagerIT.generateDID:249->newRegisteredAsset:167 » DDO Error building DD...
[ERROR]   OceanManagerIT.registerAsset:186 » DDO Error building DDO from JSON
[ERROR]   OceanManagerIT.resolveDID:211 » DDO Error building DDO from JSON
[INFO] 
[ERROR] Tests run: 24, Failures: 0, Errors: 9, Skipped: 2
```

## Step to Reproduce the problem

According to the [Business Board (Ocean Roadmap)](https://github.com/oceanprotocol/ocean/projects/1)

This is a goal: [NFRs - L2 squid-java (Must Have) #239](https://github.com/oceanprotocol/ocean/issues/239)

Which lists an uncompleted task:
- Integration tests in travis using barge #13

And #13 mentions:
```
Currently Travis is running Barge (https://github.com/oceanprotocol/squid-java/blob/develop/.travis.yml#L18). Does we need some mvn command to run the tests? 
```

From the pom.xml the integration tests are run as part of the [add-test-source goal](https://github.com/oceanprotocol/squid-java/blob/feature/tethys-rc1/pom.xml#L166)

Which adds to the [generate-test-sources](https://www.mojohaus.org/build-helper-maven-plugin/add-test-source-mojo.html) phase

Which will [generate any test source code for inclusion in compilation.](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html)

From the squid-java README we learn to run integration tests we do:
`mvn clean verify -P all-test`

NOTE (from mvn -h)
```
 -P,--activate-profiles <arg>           Comma-delimited list of profiles
                                        to activate
```
Probably wants to be `mvn clean verify -P all-tests`

Where `-P all-tests` activates the all-tests profile which mentions to [NOT skip integatration tests](https://maven.apache.org/surefire/maven-failsafe-plugin/examples/skipping-tests.html)

From the [pom.xml](https://github.com/oceanprotocol/squid-java/blob/feature/tethys-rc1/pom.xml#L330) we see that integration tests are run from the failsafe plugin as a result of the integration-test or verify goals

However `mvn verify` is currently commented out in [.travis.yml](https://github.com/oceanprotocol/squid-java/blob/feature/tethys-rc1/.travis.yml#L40)

And, as a result, the Travis badge shows squid-java passing tests when, in fact, it is ONLY passing unit tests (but failing integration tests): https://travis-ci.com/oceanprotocol/squid-java

It is possible to run the integration tests by hand as follows...

Starting with a current version of barge:

```
tmarble@cerise 787 :) git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
tmarble@cerise 788 :) git log -n 3
commit 530f0d56cac3334ccb46e4fdaa9a3f661bd6cb1f (HEAD -> develop, origin/develop, origin/HEAD)
Author: Tom Marble <tmarble@info9.net>
Date:   Mon Mar 11 09:47:16 2019 -0500

    Warn user if ~/.ocean is owned by root (#122)
    
    * Warn user if ~/.ocean is owned by root
    
    Reminder that #100 is not yet fixed
    
    * Updates start_ocean.sh
    
    Adds copyright notice (per @ttmc)
    Changes function name for file ownership to check_if_owned_by_root (per @aaitor)
    - adds a check for the KEEPER_ARTIFACTS_FOLDER (as required by --purge)
    
    Signed-off-by: Tom Marble <tmarble@info9.net>

commit 4bfd9b0ceefec02db9f0d2ff7bbf0bdf3bf7e8b4
Merge: 7d94381 ff27bca
Author: Javier Cortejoso <javier.cortejoso@gmail.com>
Date:   Wed Mar 6 12:20:14 2019 +0100

    Merge pull request #121 from oceanprotocol/feature/keeper-contracts-owner
    
    Added owner role address environment variable on Keeper contracts compose.

commit ff27bca33e7113396b2db579b7d20e20ae7b2653 (origin/feature/keeper-contracts-owner)
Author: Pedro Gutiérrez <pedrogp9693@gmail.com>
Date:   Tue Mar 5 14:29:29 2019 +0100

    Added owner role address environment variable on Keeper contracts compose
tmarble@cerise 789 :) ./start_ocean.sh --no-brizo --no-pleuston --local-spree-node --purge
```

It is worth noting this barge error on startup:
```
aquarius_1                   | [2019-03-12 20:43:40 +0000] [10] [INFO] Booting worker with pid: 10
aquarius_1                   | [2019-03-12 20:43:41 +0000] [10] [ERROR] Exception in worker process
aquarius_1                   | Traceback (most recent call last):
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
aquarius_1                   |     worker.init_process()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
aquarius_1                   |     self.load_wsgi()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
aquarius_1                   |     self.wsgi = self.app.wsgi()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
aquarius_1                   |     self.callable = self.load()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
aquarius_1                   |     return self.load_wsgiapp()
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
aquarius_1                   |     return util.import_app(self.app_uri)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
aquarius_1                   |     __import__(module)
aquarius_1                   |   File "/provider/provider/run.py", line 27, in <module>
aquarius_1                   |     from provider.app.assets import assets
aquarius_1                   |   File "/provider/provider/app/assets.py", line 18, in <module>
aquarius_1                   |     dao = Dao(config_file)
aquarius_1                   |   File "/provider/provider/app/dao.py", line 7, in __init__
aquarius_1                   |     self.oceandb = OceanDb(config_file).plugin
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/oceandb_driver_interface/oceandb.py", line 19, in __init__
aquarius_1                   |     self.plugin = start_plugin(file_path)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/oceandb_driver_interface/utils.py", line 37, in start_plugin
aquarius_1                   |     plugin_instance = load_plugin(config)
aquarius_1                   |   File "/usr/local/lib/python3.6/site-packages/oceandb_driver_interface/utils.py", line 65, in load_plugin
aquarius_1                   |     return mod.Plugin(config)
aquarius_1                   | TypeError: Can't instantiate abstract class Plugin with abstract methods text_query
aquarius_1                   | [2019-03-12 20:43:41 +0000] [10] [INFO] Worker exiting (pid: 10)
aquarius_1                   | [2019-03-12 20:43:41 +0000] [8] [INFO] Shutting down: Master
aquarius_1                   | [2019-03-12 20:43:41 +0000] [8] [INFO] Reason: Worker failed to boot.
```

Now on the latest branch of squid-java...

```
tmarble@cerise 135 :) git checkout feature/tethys-rc1
Branch 'feature/tethys-rc1' set up to track remote branch 'feature/tethys-rc1' from 'origin'.
Switched to a new branch 'feature/tethys-rc1'
tmarble@cerise 136 :) git pull
Already up to date.
tmarble@cerise 137 :) git log -n 2
commit e485d2256008aeba270c1ba9e075c1c674ed4a9b (HEAD -> feature/tethys-rc1, origin/feature/tethys-rc1)
Author: aitor@oceanprotocol.com <aitor@oceanprotocol.com>
Date:   Tue Mar 12 16:35:349 2019 +0100

    check if template was registered

commit 906a9c0e1f19ede9bc1384a4310bfe1c4f70a5a0
Author: aitor@oceanprotocol.com <aitor@oceanprotocol.com>
Date:   Tue Mar 12 15:50:50 2019 +0100

    proposing and approving template
tmarble@cerise 138 :) 
```
We can run the integration tests:
```
mvn clean verify -P all-tests > verify.log 2>&1 & 
```
_See verify.log below_

### Possible Solution

It is likely that the fix to this integration tests depends on (at least): #14, #39, #74

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version:  `commit e485d2256008aeba270c1ba9e075c1c674ed4a9b (HEAD -> feature/tethys-rc1, origin/feature/tethys-rc1) `
* Java: `openjdk version "1.8.0_191"`
* Barge:  `530f0d56cac3334ccb46e4fdaa9a3f661bd6cb1f`
* OS: `Linux cerise 4.16.0-2-amd64 #1 SMP Debian 4.16.16-2 (2018-06-22) x86_64 GNU/Linux`

## Failure Logs

[verify.log](https://github.com/oceanprotocol/squid-java/files/2958834/verify.log)

**Comment by aaitor** [comment]
![image](https://user-images.githubusercontent.com/1726644/54362936-2c95c000-466a-11e9-85e2-cd77499595e5.png)
