### ISSUE TITLE
Problem with HTTPS certificates on commons marketplace

### ISSUE THREAD

**Issue by mikera** [oceanprotocol/squid-java#99]
## Expected Behavior

Should be possible to use squid-java "out of the box" with the commons marketplace without significant configuration. 

## Current Behavior

Currently fails to get DDO for an asset due to inability to validate certificate, e.g. 

```
Exception in thread "main" 11:48:20.769 [main] ERROR com.oceanprotocol.squid.manager.OceanManager - Unable to retrieve DDO Error searching DID did:op:8e511d4c54b34454bbf7947473517a8347ada436ec034f799fdb84ce3e8683f3 onchain: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
java.lang.Error: com.oceanprotocol.squid.exceptions.DDOException: Unable to retrieve DDO Error searching DID did:op:8e511d4c54b34454bbf7947473517a8347ada436ec034f799fdb84ce3e8683f3 onchain: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
......
Caused by: com.oceanprotocol.squid.exceptions.DDOException: Unable to retrieve DDO Error searching DID did:op:8e511d4c54b34454bbf7947473517a8347ada436ec034f799fdb84ce3e8683f3 onchain: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.oceanprotocol.squid.manager.OceanManager.resolveDID(OceanManager.java:129)
	at com.oceanprotocol.squid.api.impl.AssetsImpl.resolve(AssetsImpl.java:57)
.......
```

## Step to Reproduce the problem

Failure occurs when attempting to get a DDO from an asset using the following configuration:

```java
// config from https://github.com/oceanprotocol/commons/blob/master/client/src/config.ts
		properties.put(OceanConfig.KEEPER_URL, "https://nile.dev-ocean.com");
		properties.put(OceanConfig.KEEPER_GAS_LIMIT, "4712388");
		properties.put(OceanConfig.KEEPER_GAS_PRICE, "100000000000");

		properties.put(OceanConfig.AQUARIUS_URL, "https://nginx-aquarius.dev-ocean.com");
		properties.put(OceanConfig.SECRETSTORE_URL, "https://secret-store.dev-ocean.com");

```

### Possible Solution

Options:
- Provide a facility to trust certificates by default for the commons marketplace and/or other ocean nodes explicitly trusted by the starfish-java user
- Document clearly how to install certificates locally for the commons marketplace
- Get trusted certificates for the commons marketplace

## Specifications

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version: 0.4.4
* Java: 1.8
* Barge: (Using Beta network + commons marketplace)
* OS: win

**Comment by mikera** [comment]
Additional comments:
- Seems to be a problem with older JDKs only (e.g. jdk1.8.0_40)
- Work with latest Java 11 (jdk-11.0.2)

**Comment by kremalicious** [comment]
the readme states "Squid-java requires Java 11 and Maven >= 3.5.2" so there seems to be no definition that squid-java should run on Java 8. Based on that, making it work against older versions is a new feature so should be requested in a new issue
